/*
 * Timer_Config.h
 *
 *  Created on: Sep 19, 2021
 *      Author: msqotb
 */

#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_

/* Timer0 Mode options:
 * 1- TIMER0_NORMAL_MODE
 * 2- TIMER0_PWM_PHASECORRECT_MODE
 * 3- TIMER0_CTC_MODE
 * 4- TIMER0_PWM_FAST_MODE*/
#define TIMER0_MODE TIMER0_CTC_MODE

/*PRESCALER OPTIONS:
 *1-TIMER0_NO_PRESCALER
 *2-TIMER0_8_PRESCALER
 *3-TIMER0_64_PRESCALER
 *4-TIMER0_256_PRESCALER
 *5-TIMER0_1024_PRESCALER
 *6-TIMER0_EXTERNAL_SOURCE_FALLING
 *7-TIMER0_EXTERNAL_SOURCE_RISING */
#define TIMER0_PRESCALER	TIMER0_256_PRESCALER

/*OC0_PIN MODE IN CTC MODE OPTIONS:
 * 1-OC0_PIN_DISCONNECTED
 * 2-OC0_PIN_TOGGLE
 * 3-OC0_PIN_CLEAR
 * 4-OC0_PIN_SET
 * */
/*OC0_PIN MODE IN FAST_PWM MODE OPTIONS:
 * 1*OC0_PIN_CLEAR		//first high
 * 2-OC0_PIN_SET
 * */
/*OC0_PIN MODE IN PWM_PHASECORRECT MODE OPTIONS:
 * 1-OC0_PIN_CLEAR		//first high
 * 2-OC0_PIN_SET
 * */

#define OC0_PIN_MODE	OC0_PIN_DISCONNECTED

#endif /* TIMER_CONFIG_H_ */
